/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameLocadora.java
 *
 * Created on 26/10/2011, 22:54:06
 */
package usuario;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilitarios.LtpUtil;
import dados.*;
import locnegocio.LocNegocio;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;

/**
 *
 * @author JP
 */
public class JFrameLocar extends javax.swing.JFrame {

    //Member
    private static LocNegocio m_loc = new LocNegocio();

    /** Creates new form JFrameClintes */
    public JFrameLocar() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icone = new ImageIcon(getClass().getResource("recursos/switchuser.png"));
        setIconImage(icone.getImage());
        setVisible(true);
        jFormattedTextFieldCodFilme.requestFocus();
        Thread horario = new Thread(new Runnable() {

            public void run() {
                while (true) {
                    jLabelHora.setText(new SimpleDateFormat("HH:mm:ss").format(new GregorianCalendar().getTime()));
                    jLabelHora1.setText(jLabelHora.getText());
                    jLabelHora2.setText(jLabelHora.getText());
                    try {
                        Thread.sleep(1000); // Interromper por 1000 milisegundos
                    } catch (InterruptedException e) {
                    }
                }
            }
        });
        horario.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonClientes = new javax.swing.JButton();
        jButtonFilmes = new javax.swing.JButton();
        jButtonLocacao = new javax.swing.JButton();
        jButton3D = new javax.swing.JButton();
        jLabelClientes = new javax.swing.JLabel();
        jLabelFilmes = new javax.swing.JLabel();
        jLabelLocacao = new javax.swing.JLabel();
        jLabel3D = new javax.swing.JLabel();
        jTabbedPaneClientes = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        jPanelFichaCadastro = new javax.swing.JPanel();
        jFormattedTextFieldCodFilme = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataLoc = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataDev = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCodCliente = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanelComandos = new javax.swing.JPanel();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonRestaurar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonPrimeiro1 = new javax.swing.JButton();
        jLabelHora = new javax.swing.JLabel();
        jPanelConsulta = new javax.swing.JPanel();
        jPanelParametro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButtonExecutarPesquisa = new javax.swing.JButton();
        jPanelResposta = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabelHora1 = new javax.swing.JLabel();
        jPanelConsulta3 = new javax.swing.JPanel();
        jPanelParametro5 = new javax.swing.JPanel();
        jLabel188 = new javax.swing.JLabel();
        jButtonExecutarRelatorio = new javax.swing.JButton();
        jTextFieldParametrofim = new javax.swing.JTextField();
        jTextFieldParametroinicio = new javax.swing.JTextField();
        jLabel189 = new javax.swing.JLabel();
        jLabelHora2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemFechar = new javax.swing.JMenuItem();
        jMenuTemas = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Locadora LTDA - Clientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(233, 233, 247));

        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/User-Clients-icon.png"))); // NOI18N
        jButtonClientes.setFocusPainted(false);
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonFilmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/Movies-icon.png"))); // NOI18N
        jButtonFilmes.setFocusPainted(false);
        jButtonFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilmesActionPerformed(evt);
            }
        });

        jButtonLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/Film-Maker-Male-Light-icon.png"))); // NOI18N
        jButtonLocacao.setFocusPainted(false);
        jButtonLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocacaoActionPerformed(evt);
            }
        });

        jButton3D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/3D-Penguins-icon.png"))); // NOI18N
        jButton3D.setFocusPainted(false);
        jButton3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3DActionPerformed(evt);
            }
        });

        jLabelClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelClientes.setForeground(new java.awt.Color(153, 153, 153));
        jLabelClientes.setText("Clientes");

        jLabelFilmes.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelFilmes.setForeground(new java.awt.Color(153, 153, 153));
        jLabelFilmes.setText("Filmes");

        jLabelLocacao.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelLocacao.setForeground(new java.awt.Color(153, 153, 153));
        jLabelLocacao.setText("Locação");

        jLabel3D.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel3D.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3D.setText("3D");

        jPanelFichaCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Ficha de Cadastro de Locação", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Código");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Código Do Filme");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Data da Locação");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Data da Devolução");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Código Do Cliente");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Valor");

        jTextFieldCodigo.setEditable(false);

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("dd/MM/yyyy");

        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("dd/MM/yyyy");

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/US-dollar-icon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("1.50/dia");

        javax.swing.GroupLayout jPanelFichaCadastroLayout = new javax.swing.GroupLayout(jPanelFichaCadastro);
        jPanelFichaCadastro.setLayout(jPanelFichaCadastroLayout);
        jPanelFichaCadastroLayout.setHorizontalGroup(
            jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFichaCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFormattedTextFieldDataLoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldDataDev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFormattedTextFieldCodFilme, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jFormattedTextFieldCodCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(278, 278, 278))
        );
        jPanelFichaCadastroLayout.setVerticalGroup(
            jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldCodFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDataLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelComandos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Comandos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jButtonPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/primeiro.gif"))); // NOI18N
        jButtonPrimeiro.setToolTipText("Primeiro");
        jButtonPrimeiro.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/anterior.gif"))); // NOI18N
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/proximo.gif"))); // NOI18N
        jButtonProximo.setToolTipText("Próximo");
        jButtonProximo.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/ultimo.gif"))); // NOI18N
        jButtonUltimo.setToolTipText("Último");
        jButtonUltimo.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/inserir.gif"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/remover.gif"))); // NOI18N
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/editar.gif"))); // NOI18N
        jButtonEditar.setToolTipText("Alterar");
        jButtonEditar.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/atualizar.gif"))); // NOI18N
        jButtonRestaurar.setToolTipText("Restaurar");
        jButtonRestaurar.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaurarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/buscar.gif"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar");
        jButtonPesquisar.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/fexit.gif"))); // NOI18N
        jButtonSair.setToolTipText("Fechar");
        jButtonSair.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonPrimeiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/broom.gif"))); // NOI18N
        jButtonPrimeiro1.setToolTipText("Limpar");
        jButtonPrimeiro.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPrimeiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComandosLayout = new javax.swing.GroupLayout(jPanelComandos);
        jPanelComandos.setLayout(jPanelComandosLayout);
        jPanelComandosLayout.setHorizontalGroup(
            jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComandosLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrimeiro1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        jPanelComandosLayout.setVerticalGroup(
            jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComandosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonRestaurar)
                    .addComponent(jButtonPrimeiro1)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonIncluir.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora.setText("Hora");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelComandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFichaCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addComponent(jLabelHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFichaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelComandos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPaneClientes.addTab("Cadastro", jPanelCadastro);

        jPanelParametro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Consulta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Locações de filmes com atraso na devolução.");
        jLabel5.setMaximumSize(new java.awt.Dimension(300, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(300, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(300, 14));

        jButtonExecutarPesquisa.setMnemonic('E');
        jButtonExecutarPesquisa.setText("Consultar");
        jButtonExecutarPesquisa.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutarPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutarPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelParametroLayout = new javax.swing.GroupLayout(jPanelParametro);
        jPanelParametro.setLayout(jPanelParametroLayout);
        jPanelParametroLayout.setHorizontalGroup(
            jPanelParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButtonExecutarPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanelParametroLayout.setVerticalGroup(
            jPanelParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametroLayout.createSequentialGroup()
                .addGroup(jPanelParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExecutarPesquisa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelResposta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Resposta em ordem do nome do cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(jTableClientes);

        javax.swing.GroupLayout jPanelRespostaLayout = new javax.swing.GroupLayout(jPanelResposta);
        jPanelResposta.setLayout(jPanelRespostaLayout);
        jPanelRespostaLayout.setHorizontalGroup(
            jPanelRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRespostaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRespostaLayout.setVerticalGroup(
            jPanelRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRespostaLayout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelHora1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora1.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora1.setText("Hora");

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelParametro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHora1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addComponent(jLabelHora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneClientes.addTab("Pesquisa", jPanelConsulta);

        jPanelParametro5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Parâmetro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel188.setForeground(new java.awt.Color(102, 102, 102));
        jLabel188.setText("Período");

        jButtonExecutarRelatorio.setMnemonic('E');
        jButtonExecutarRelatorio.setText("Relatório");
        jButtonExecutarRelatorio.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutarPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarRelatorioActionPerformed(evt);
            }
        });

        jLabel189.setForeground(new java.awt.Color(102, 102, 102));
        jLabel189.setText("à");

        javax.swing.GroupLayout jPanelParametro5Layout = new javax.swing.GroupLayout(jPanelParametro5);
        jPanelParametro5.setLayout(jPanelParametro5Layout);
        jPanelParametro5Layout.setHorizontalGroup(
            jPanelParametro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel188)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldParametroinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel189)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldParametrofim, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButtonExecutarRelatorio)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanelParametro5Layout.setVerticalGroup(
            jPanelParametro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro5Layout.createSequentialGroup()
                .addGroup(jPanelParametro5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel188)
                    .addComponent(jLabel189)
                    .addComponent(jTextFieldParametrofim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldParametroinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExecutarRelatorio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelHora2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanelConsulta3Layout = new javax.swing.GroupLayout(jPanelConsulta3);
        jPanelConsulta3.setLayout(jPanelConsulta3Layout);
        jPanelConsulta3Layout.setHorizontalGroup(
            jPanelConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsulta3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelParametro5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelConsulta3Layout.setVerticalGroup(
            jPanelConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta3Layout.createSequentialGroup()
                .addComponent(jLabelHora2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParametro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        jTabbedPaneClientes.addTab("Relatório", jPanelConsulta3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPaneClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabelClientes)
                        .addGap(115, 115, 115)
                        .addComponent(jLabelFilmes)
                        .addGap(116, 116, 116)
                        .addComponent(jLabelLocacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(jLabel3D)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3D, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClientes)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3D, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonLocacao)
                        .addComponent(jButtonFilmes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientes)
                    .addComponent(jLabelFilmes)
                    .addComponent(jLabelLocacao)
                    .addComponent(jLabel3D))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPaneClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuArquivo.setText("Arquivo");

        jMenuItemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/button_cancel.png"))); // NOI18N
        jMenuItemFechar.setText("Fechar");
        jMenuItemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFecharActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemFechar);

        jMenuBar1.add(jMenuArquivo);

        jMenuTemas.setText("Temas");
        jMenuBar1.add(jMenuTemas);

        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre o aplicativo...");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        utilitarios.UsarSustance.substanceLtpUtil(jMenuTemas);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        new jDialogSobre(this, true);
}//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFecharActionPerformed
        fechar();
}//GEN-LAST:event_jMenuItemFecharActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        JFrameClientes JF_Clientes = new JFrameClientes();
        JF_Clientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        primeiro();
}//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        anterior();
}//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        proximo();
}//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        ultimo();
}//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        if (validarAtualizacao() == false) {
            return;
        }
        int codigoCab = 0;
        int codigoDet = 0;
        int controle = 0;
        if (jTextFieldCodigo.getText().equals((""))) {
            try {
                codigoCab = (m_loc.buscaLocacaoUltimo().getCodigoCab()) + 1;
            } catch (Exception ex) {
                codigoCab = 1;
            }
        } else {
            try {
                codigoCab = Integer.parseInt(jTextFieldCodigo.getText());
                controle = 1;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                        "Cadastro de Locações", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        try {
            codigoDet = (m_loc.buscaLocacaoUltimo().getCodigoDet()) + 1;
        } catch (Exception ex) {
            codigoDet = 1;
        }

        try {
            DateFormat formaterLoc = new SimpleDateFormat("dd/MM/yyyy");
            String dtLoc = jFormattedTextFieldDataLoc.getText();
            java.util.Date parsedUtilDateLoc = formaterLoc.parse(dtLoc);
            java.sql.Date DataLoc = new java.sql.Date(parsedUtilDateLoc.getTime());

            java.sql.Date DataDev = null;

            if (!jFormattedTextFieldDataDev.getText().equals("")) {

                if (!LtpUtil.validarData(jFormattedTextFieldDataDev.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Data de Devolução Inválida.",
                            "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
                    jFormattedTextFieldDataDev.requestFocus();
                    return;
                }
                DateFormat formaterDev = new SimpleDateFormat("dd/MM/yyyy");
                String dtDev = jFormattedTextFieldDataDev.getText();
                java.util.Date parsedUtilDateDev = formaterDev.parse(dtDev);
                DataDev = new java.sql.Date(parsedUtilDateDev.getTime());
            }

            int codCliente = Integer.parseInt(jFormattedTextFieldCodCliente.getText());
            int codFilme = Integer.parseInt(jFormattedTextFieldCodFilme.getText());

            Double valor = 0.0;

            if (!jFormattedTextFieldValor.getText().equals("")) {
                try {
                    valor = Double.parseDouble(jFormattedTextFieldValor.getText());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                            "Cadastro de Locações", JOptionPane.INFORMATION_MESSAGE);
                }
            }

            m_loc.adicionarLocacao(new Locacao(codigoCab, codCliente, DataLoc, DataDev, codigoDet, codFilme, valor));

            if (controle == 0) {
                JOptionPane.showMessageDialog(this, "Locação Cadastrada.",
                        "Cadastro de Locações", JOptionPane.INFORMATION_MESSAGE);
            } else {

                JOptionPane.showMessageDialog(this, "Filme Adicionado.",
                        "Cadastro de Locações", JOptionPane.INFORMATION_MESSAGE);

            }
            limparForm();


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                    "Cadastro de Locações", JOptionPane.INFORMATION_MESSAGE);
        }

}//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTextFieldCodigo.getText().equals("") || jTextFieldCodigo == null) {
            return;
        }
        if (JOptionPane.showConfirmDialog(null, "Confirmar a exclusão da locação - "
                + jFormattedTextFieldCodFilme.getText().trim() + "?",
                "Cadastro de Locações",
                JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            m_loc.excluirCliente(Integer.parseInt(jTextFieldCodigo.getText()));
            JOptionPane.showMessageDialog(this, "Locação Excluída.",
                    "Cadastro de Locações", JOptionPane.INFORMATION_MESSAGE);
            limparForm();

        } catch (SQLException objErro) {
            JOptionPane.showMessageDialog(this, objErro.getMessage(),
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);

        }
}//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if (validarAtualizacao() == false) {
            return;
        }
        if (jTextFieldCodigo.getText() == null || !jTextFieldCodigo.getText().matches("[0-9]*") || jTextFieldCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo código vazio.",
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
            jTextFieldCodigo.requestFocus();
            return;
        }
        int codigoDet = 0;
        try {
            codigoDet = (m_loc.buscaLocacaoUltimo().getCodigoDet());
        } catch (Exception ex) {
            codigoDet = 1;
        }
        try {
            DateFormat formaterLoc = new SimpleDateFormat("dd/MM/yyyy");
            String dtLoc = jFormattedTextFieldDataLoc.getText();
            java.util.Date parsedUtilDateLoc = formaterLoc.parse(dtLoc);
            java.sql.Date DataLoc = new java.sql.Date(parsedUtilDateLoc.getTime());

            java.sql.Date DataDev = null;

            if (!jFormattedTextFieldDataDev.getText().equals("")) {

                if (!LtpUtil.validarData(jFormattedTextFieldDataDev.getText().trim())) {
                    JOptionPane.showMessageDialog(this, "Data de Devolução Inválida.",
                            "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
                    jFormattedTextFieldDataDev.requestFocus();
                    return;
                }
                DateFormat formaterDev = new SimpleDateFormat("dd/MM/yyyy");
                String dtDev = jFormattedTextFieldDataDev.getText();
                java.util.Date parsedUtilDateDev = formaterDev.parse(dtDev);
                DataDev = new java.sql.Date(parsedUtilDateDev.getTime());
            }
            int codigoCab = Integer.parseInt(jTextFieldCodigo.getText());
            int codCliente = Integer.parseInt(jFormattedTextFieldCodCliente.getText());
            int codFilme = Integer.parseInt(jFormattedTextFieldCodFilme.getText());
            double valor = Double.parseDouble(jFormattedTextFieldValor.getText());

            m_loc.alterarLocacao(new Locacao(codigoCab, codCliente, DataLoc, DataDev, codigoDet, codFilme, valor));

            JOptionPane.showMessageDialog(this, "Locação Alterada.",
                    "Cadastro de Locações", JOptionPane.INFORMATION_MESSAGE);
            limparForm();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                    "Cadastro de Locações", JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaurarActionPerformed
        if (jTextFieldCodigo.getText() == null || !jTextFieldCodigo.getText().matches("[0-9]*") || jTextFieldCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo código vazio.",
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
            jTextFieldCodigo.requestFocus();
            return;
        }
        exibirLocacaoCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
}//GEN-LAST:event_jButtonRestaurarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        String codigo = JOptionPane.showInputDialog(this, "Informe o código do cliente", "Cadastro de Clientes", JOptionPane.QUESTION_MESSAGE);
        if (codigo == null || !codigo.matches("[0-9]*") || codigo.equals("")) {
            return;
        }
        exibirLocacaoCodigo(Integer.parseInt(codigo));
}//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        fechar();
}//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonExecutarPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarPesquisaActionPerformed
        /*Vector<Cliente> listaClientes = null;
        try {
        jTextAreaResposta.setText("");
        listaClientes = m_loc.buscarClientesPorNome(jTextFieldParametroNome.getText().trim());
        for (Cliente objCliente : listaClientes) {
        jTextAreaResposta.append(objCliente.toString() + "\n");
        }
        jTextAreaResposta.append("Nº de clientes encontrados: " + listaClientes.size() + "\n");
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(),
        "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
        }*/
        try {
            jScrollPane10.setViewportView(m_loc.buscarLocacoesPorData());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Consulta de Locações com Atraso",
                    JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_jButtonExecutarPesquisaActionPerformed

    private void jButtonFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilmesActionPerformed

        JFrameFilmes JF_Filmes = new JFrameFilmes();
        JF_Filmes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFilmesActionPerformed

    private void jButtonPrimeiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiro1ActionPerformed
        limparForm();
    }//GEN-LAST:event_jButtonPrimeiro1ActionPerformed

    private void jButtonLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocacaoActionPerformed
        JFrameLocadora JF_Loc = new JFrameLocadora();
        JF_Loc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLocacaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jFormattedTextFieldDataLoc.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Campo Data de Locação Vazio.",
                    "Cadastro de Locações",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jFormattedTextFieldDataDev.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Campo Data de Devolução Vazio.",
                    "Cadastro de Locações",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            GregorianCalendar calendaDev = convertDateString(jFormattedTextFieldDataDev.getText());
            GregorianCalendar calendaLoc = convertDateString(jFormattedTextFieldDataLoc.getText());

            long retorno = LtpUtil.subtrairDatas(calendaLoc, calendaDev);
            double valor = retorno * 1.50;
            jFormattedTextFieldValor.setText(String.valueOf(valor));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Cadastro de Locações",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonExecutarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarRelatorioActionPerformed
GregorianCalendar menorData = new GregorianCalendar();
        GregorianCalendar maiorData = new GregorianCalendar();

        if (!LtpUtil.validarData(jTextFieldParametroinicio.getText(), menorData)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Menor data inválida.",
                    "Relação de Clientes",
                    JOptionPane.WARNING_MESSAGE);
            jTextFieldParametroinicio.requestFocus();
            return;
        }
        if (!LtpUtil.validarData(jTextFieldParametrofim.getText(), maiorData)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Maior data inválida.",
                    "Relação de Clientes",
                    JOptionPane.WARNING_MESSAGE);
            jTextFieldParametrofim.requestFocus();
            return;
        }
        if (menorData.compareTo(maiorData)>0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Menor data maior que a maior data",
                    "Relação de Clientes",
                    JOptionPane.WARNING_MESSAGE);
            jTextFieldParametroinicio.requestFocus();
            return;
        }
        HashMap<String,Object> parametros = new HashMap<String, Object>();
        parametros.put("DATA", menorData.getTime());
        parametros.put("DATA2", maiorData.getTime());

        try {
            LtpUtil.gerarRelatorio(
                    LtpUtil.RELATORIO_VISUALIZADOR_JASPER,
                    bdlocadora.BDLocadora.objCon,
                    parametros,
                    getClass().getResource("relatorios/Relatorio_L.jasper").openStream(),
                    "Relação de Locações de Filmes");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jButtonExecutarRelatorioActionPerformed

    private void jButton3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3DActionPerformed
        JFrame3D JF_3D = new JFrame3D(this, true);
        JF_3D.setVisible(true);
    }//GEN-LAST:event_jButton3DActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3D;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExecutarPesquisa;
    private javax.swing.JButton jButtonExecutarRelatorio;
    private javax.swing.JButton jButtonFilmes;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLocacao;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonPrimeiro1;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonRestaurar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldCodFilme;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataDev;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataLoc;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3D;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelFilmes;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelHora1;
    private javax.swing.JLabel jLabelHora2;
    private javax.swing.JLabel jLabelLocacao;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemFechar;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuTemas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelComandos;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelConsulta3;
    private javax.swing.JPanel jPanelFichaCadastro;
    private javax.swing.JPanel jPanelParametro;
    private javax.swing.JPanel jPanelParametro5;
    private javax.swing.JPanel jPanelResposta;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTabbedPane jTabbedPaneClientes;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldParametrofim;
    private javax.swing.JTextField jTextFieldParametroinicio;
    // End of variables declaration//GEN-END:variables

    public GregorianCalendar convertDateString(String dateString) throws Exception {

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date date = sdf.parse(dateString);
        Calendar calender = new GregorianCalendar();
        calender.setTime(date);

        return (GregorianCalendar) calender;

    }

    private void fechar() {
        if (JOptionPane.showConfirmDialog(
                this,
                "Confirma a saída?",
                "Locadora",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            try {
                bdlocadora.BDLocadora.fecharConexao();
                dispose();
                System.exit(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                System.exit(1);
            }

        }
    }

    private void primeiro() {
        try {
            exibirLocacao(m_loc.buscarLocacaoPrimeiro());
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void anterior() {
        try {
            if (jTextFieldCodigo.getText().equals("") || jTextFieldCodigo == null) {
                primeiro();
                return;
            }
            exibirLocacao(m_loc.buscarLocacaoAnterior(Integer.parseInt(jTextFieldCodigo.getText())));
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void proximo() {
        try {
            if (jTextFieldCodigo.getText().equals("") || jTextFieldCodigo == null) {
                primeiro();
                return;
            }
            exibirLocacao(m_loc.buscarLocacaoProximo(Integer.parseInt(jTextFieldCodigo.getText())));
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void ultimo() {
        try {
            exibirLocacao(m_loc.buscaLocacaoUltimo());
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void exibirLocacaoCodigo(int codigo) {
        try {
            exibirLocacao(m_loc.buscarLocacaoPorCodigo(codigo));
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void exibirLocacao(Locacao obj) {
        jTextFieldCodigo.setText(String.valueOf(obj.getCodigoCab()));
        jFormattedTextFieldCodCliente.setText(String.valueOf(obj.getCodigoCliente()));
        jFormattedTextFieldDataLoc.setText(LtpUtil.formatarData(obj.getDataLocacao(), "dd/MM/yyyy"));

        if (obj.getDataDevolucao() != null) {
            jFormattedTextFieldDataDev.setText(LtpUtil.formatarData(obj.getDataDevolucao(), "dd/MM/yyyy"));
        }
        jFormattedTextFieldCodFilme.setText(String.valueOf(obj.getCodigoFilme()));
        jFormattedTextFieldValor.setText(obj.getValor().toString());
    }

    private void limparForm() {
        jTextFieldCodigo.setText("");
        jFormattedTextFieldCodCliente.setText("");
        jFormattedTextFieldDataLoc.setText("");
        jFormattedTextFieldDataDev.setText("");
        jFormattedTextFieldCodFilme.setText("");
        jFormattedTextFieldValor.setText("");
    }

    private boolean validarAtualizacao() {

        if (jFormattedTextFieldCodFilme.getText().trim().equals("") || !jFormattedTextFieldCodFilme.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(this, "Código do Filme Inválido.",
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldCodFilme.requestFocus();
            return false;
        }
        if (jFormattedTextFieldCodCliente.getText().trim().equals("")
                || !jFormattedTextFieldCodCliente.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(this, "Código do Cliente Inválido.",
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldCodCliente.requestFocus();
            return false;
        }
        if (!jFormattedTextFieldDataLoc.getText().trim().equals("")
                && !LtpUtil.validarData(jFormattedTextFieldDataLoc.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Data de Locação Inválida.",
                    "Cadastro de Locações", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldDataLoc.requestFocus();
            return false;
        }
        return true;
    }

    public boolean isDouble(String str) {
        try {
            Double.parseDouble(str);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
}
