/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameLocadora.java
 *
 * Created on 26/10/2011, 22:54:06
 */
package usuario;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilitarios.LtpUtil;
import dados.*;
import java.sql.ResultSet;
import locnegocio.LocNegocio;
import java.text.DateFormat;
import java.util.GregorianCalendar;
import java.util.HashMap;

/**
 *
 * @author JP
 */
public class JFrameFilmes extends javax.swing.JFrame {

    //Member
    private static LocNegocio m_loc = new LocNegocio();

    /** Creates new form JFrameFilmes */
    public JFrameFilmes() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icone = new ImageIcon(getClass().getResource("recursos/switchuser.png"));
        setIconImage(icone.getImage());
        setVisible(true);
        jFormattedTextFieldBrasil.requestFocus();
        Thread horario = new Thread(new Runnable() {

            public void run() {
                while (true) {
                    jLabelHora.setText(new SimpleDateFormat("HH:mm:ss").format(new GregorianCalendar().getTime()));
                    jLabelHora1.setText(jLabelHora.getText());
                    jLabelHora2.setText(jLabelHora.getText());
                    jLabelHora3.setText(jLabelHora.getText());
                    jLabelHora4.setText(jLabelHora.getText());
                    try {
                        Thread.sleep(1000); // Interromper por 1000 milisegundos
                    } catch (InterruptedException e) {
                    }
                }
            }
        });
        horario.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonClientes = new javax.swing.JButton();
        jButtonFilmes = new javax.swing.JButton();
        jButtonLocacao = new javax.swing.JButton();
        jButton3D = new javax.swing.JButton();
        jLabelClientes = new javax.swing.JLabel();
        jLabelFilmes = new javax.swing.JLabel();
        jLabelLocacao = new javax.swing.JLabel();
        jLabel3D = new javax.swing.JLabel();
        jTabbedPaneClientes12 = new javax.swing.JTabbedPane();
        jPanelCadastro12 = new javax.swing.JPanel();
        jPanelFichaCadastro12 = new javax.swing.JPanel();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jFormattedTextFieldAtor = new javax.swing.JFormattedTextField();
        jLabel175 = new javax.swing.JLabel();
        jFormattedTextFieldVotos = new javax.swing.JFormattedTextField();
        jLabel176 = new javax.swing.JLabel();
        jFormattedTextFieldPontos = new javax.swing.JFormattedTextField();
        jFormattedTextFieldAno = new javax.swing.JFormattedTextField();
        jFormattedTextFieldBrasil = new javax.swing.JFormattedTextField();
        jFormattedTextFieldGenero = new javax.swing.JFormattedTextField();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabel177 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jFormattedTextFieldDiaria = new javax.swing.JFormattedTextField();
        jLabel179 = new javax.swing.JLabel();
        jFormattedTextFieldEmprestado = new javax.swing.JFormattedTextField();
        jFormattedTextFieldEstoque = new javax.swing.JFormattedTextField();
        jLabel180 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jFormattedTextFieldTempo = new javax.swing.JFormattedTextField();
        jLabel182 = new javax.swing.JLabel();
        jScrollPaneResumo = new javax.swing.JScrollPane();
        jFormattedTextFieldResumo = new javax.swing.JTextArea();
        jFormattedTextFieldOriginal = new javax.swing.JFormattedTextField();
        jLabelHora = new javax.swing.JLabel();
        jPanelComandos1 = new javax.swing.JPanel();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonRestaurar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonPrimeiro1 = new javax.swing.JButton();
        jPanelConsulta = new javax.swing.JPanel();
        jPanelParametro = new javax.swing.JPanel();
        jTextFieldParametroNome = new javax.swing.JTextField();
        jLabel183 = new javax.swing.JLabel();
        jButtonExecutaPesquisa = new javax.swing.JButton();
        jPanelResposta = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableFilmes = new javax.swing.JTable();
        jLabelHora1 = new javax.swing.JLabel();
        jPanelConsulta3 = new javax.swing.JPanel();
        jPanelParametro2 = new javax.swing.JPanel();
        jTextFieldParametroNome2 = new javax.swing.JTextField();
        jLabel185 = new javax.swing.JLabel();
        jButtonExecutaPesquisaAlugados = new javax.swing.JButton();
        jPanelResposta3 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTableFilmes3 = new javax.swing.JTable();
        jLabelHora4 = new javax.swing.JLabel();
        jPanelConsulta2 = new javax.swing.JPanel();
        jPanelResposta1 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTableFilmes1 = new javax.swing.JTable();
        jLabelHora2 = new javax.swing.JLabel();
        jPanelParametro4 = new javax.swing.JPanel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jTextFieldParametroValue = new javax.swing.JTextField();
        jTextFieldParametroLoc = new javax.swing.JTextField();
        jPanelParametro6 = new javax.swing.JPanel();
        jLabel190 = new javax.swing.JLabel();
        jButtonExecutarConsulta = new javax.swing.JButton();
        jTextFieldParametroData4 = new javax.swing.JTextField();
        jTextFieldParametroData3 = new javax.swing.JTextField();
        jLabel191 = new javax.swing.JLabel();
        jPanelConsulta4 = new javax.swing.JPanel();
        jPanelParametro7 = new javax.swing.JPanel();
        jButtonExecutarRelatorio = new javax.swing.JButton();
        jLabelHora3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemFechar = new javax.swing.JMenuItem();
        jMenuTemas = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Locadora LTDA - Filmes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(233, 233, 247));

        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/User-Clients-icon.png"))); // NOI18N
        jButtonClientes.setFocusPainted(false);
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonFilmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/Movies-icon.png"))); // NOI18N
        jButtonFilmes.setFocusPainted(false);
        jButtonFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilmesActionPerformed(evt);
            }
        });

        jButtonLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/Film-Maker-Male-Light-icon.png"))); // NOI18N
        jButtonLocacao.setFocusPainted(false);
        jButtonLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocacaoActionPerformed(evt);
            }
        });

        jButton3D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/3D-Penguins-icon.png"))); // NOI18N
        jButton3D.setFocusPainted(false);
        jButton3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3DActionPerformed(evt);
            }
        });

        jLabelClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelClientes.setForeground(new java.awt.Color(153, 153, 153));
        jLabelClientes.setText("Clientes");

        jLabelFilmes.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelFilmes.setForeground(new java.awt.Color(153, 153, 153));
        jLabelFilmes.setText("Filmes");

        jLabelLocacao.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelLocacao.setForeground(new java.awt.Color(153, 153, 153));
        jLabelLocacao.setText("Locação");

        jLabel3D.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel3D.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3D.setText("3D");

        jPanelFichaCadastro12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Ficha de Cadastro de Filmes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel169.setForeground(new java.awt.Color(102, 102, 102));
        jLabel169.setText("Código");

        jLabel170.setForeground(new java.awt.Color(102, 102, 102));
        jLabel170.setText("Nome Brasil");

        jLabel171.setForeground(new java.awt.Color(102, 102, 102));
        jLabel171.setText("Ano");

        jLabel172.setForeground(new java.awt.Color(102, 102, 102));
        jLabel172.setText("Gênero Principal");

        jLabel173.setForeground(new java.awt.Color(102, 102, 102));
        jLabel173.setText("Nome Original");

        jLabel174.setForeground(new java.awt.Color(102, 102, 102));
        jLabel174.setText("Ator Principal");

        jTextFieldCodigo.setEditable(false);

        jFormattedTextFieldAtor.setMaximumSize(new java.awt.Dimension(6, 20));

        jLabel175.setForeground(new java.awt.Color(102, 102, 102));
        jLabel175.setText("Pontuação IMDB");

        jFormattedTextFieldVotos.setMaximumSize(new java.awt.Dimension(6, 20));

        jLabel176.setForeground(new java.awt.Color(102, 102, 102));
        jLabel176.setText("Qtd Votos IMDB");

        jFormattedTextFieldPontos.setMaximumSize(new java.awt.Dimension(6, 20));

        jFormattedTextFieldAno.setMaximumSize(new java.awt.Dimension(6, 20));

        jFormattedTextFieldBrasil.setMaximumSize(new java.awt.Dimension(6, 20));

        jFormattedTextFieldGenero.setMaximumSize(new java.awt.Dimension(6, 20));

        jFormattedTextFieldData.setMaximumSize(new java.awt.Dimension(6, 20));

        jLabel177.setForeground(new java.awt.Color(102, 102, 102));
        jLabel177.setText("Data Filme");

        jLabel178.setForeground(new java.awt.Color(102, 102, 102));
        jLabel178.setText("Diária");

        jFormattedTextFieldDiaria.setMaximumSize(new java.awt.Dimension(6, 20));

        jLabel179.setForeground(new java.awt.Color(102, 102, 102));
        jLabel179.setText("Emprestados");

        jFormattedTextFieldEmprestado.setMaximumSize(new java.awt.Dimension(6, 20));

        jLabel180.setForeground(new java.awt.Color(102, 102, 102));
        jLabel180.setText("Tempo de Filme");

        jLabel181.setForeground(new java.awt.Color(102, 102, 102));
        jLabel181.setText("Estoque");

        jFormattedTextFieldTempo.setMaximumSize(new java.awt.Dimension(6, 20));

        jLabel182.setForeground(new java.awt.Color(102, 102, 102));
        jLabel182.setText("Resumo IMDB");

        jFormattedTextFieldResumo.setColumns(20);
        jFormattedTextFieldResumo.setRows(5);
        jFormattedTextFieldResumo.setMaximumSize(new java.awt.Dimension(4, 22));
        jScrollPaneResumo.setViewportView(jFormattedTextFieldResumo);

        jFormattedTextFieldOriginal.setMaximumSize(new java.awt.Dimension(6, 20));

        javax.swing.GroupLayout jPanelFichaCadastro12Layout = new javax.swing.GroupLayout(jPanelFichaCadastro12);
        jPanelFichaCadastro12.setLayout(jPanelFichaCadastro12Layout);
        jPanelFichaCadastro12Layout.setHorizontalGroup(
            jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaCadastro12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel169)
                    .addComponent(jLabel170)
                    .addComponent(jLabel174)
                    .addComponent(jLabel173)
                    .addComponent(jLabel172)
                    .addComponent(jLabel171)
                    .addComponent(jLabel175)
                    .addComponent(jLabel182))
                .addGap(33, 33, 33)
                .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFichaCadastro12Layout.createSequentialGroup()
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFormattedTextFieldGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jFormattedTextFieldAtor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jFormattedTextFieldPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldBrasil, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel177)
                            .addComponent(jLabel176)
                            .addComponent(jLabel178)
                            .addComponent(jLabel179)
                            .addComponent(jLabel181)
                            .addComponent(jLabel180))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextFieldVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldEmprestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldEstoque)
                            .addComponent(jFormattedTextFieldTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldDiaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPaneResumo))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanelFichaCadastro12Layout.setVerticalGroup(
            jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaCadastro12Layout.createSequentialGroup()
                .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFichaCadastro12Layout.createSequentialGroup()
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel169)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel170)
                            .addComponent(jFormattedTextFieldBrasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel173)
                            .addComponent(jFormattedTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel171))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel172))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel174)
                            .addComponent(jFormattedTextFieldAtor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFichaCadastro12Layout.createSequentialGroup()
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel180))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel181))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldEmprestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel179))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel178))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel177))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel175)
                    .addComponent(jFormattedTextFieldPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldVotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel176))
                .addGroup(jPanelFichaCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFichaCadastro12Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel182))
                    .addGroup(jPanelFichaCadastro12Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPaneResumo, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora.setText("Hora");

        jPanelComandos1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Comandos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jButtonPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/primeiro.gif"))); // NOI18N
        jButtonPrimeiro.setToolTipText("Primeiro");
        jButtonPrimeiro.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/anterior.gif"))); // NOI18N
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/proximo.gif"))); // NOI18N
        jButtonProximo.setToolTipText("Próximo");
        jButtonProximo.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/ultimo.gif"))); // NOI18N
        jButtonUltimo.setToolTipText("Último");
        jButtonUltimo.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/inserir.gif"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/remover.gif"))); // NOI18N
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/editar.gif"))); // NOI18N
        jButtonEditar.setToolTipText("Alterar");
        jButtonEditar.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/atualizar.gif"))); // NOI18N
        jButtonRestaurar.setToolTipText("Restaurar");
        jButtonRestaurar.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaurarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/buscar.gif"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar");
        jButtonPesquisar.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/fexit.gif"))); // NOI18N
        jButtonSair.setToolTipText("Fechar");
        jButtonSair.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonPrimeiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/broom.gif"))); // NOI18N
        jButtonPrimeiro1.setToolTipText("Limpar");
        jButtonPrimeiro.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPrimeiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComandos1Layout = new javax.swing.GroupLayout(jPanelComandos1);
        jPanelComandos1.setLayout(jPanelComandos1Layout);
        jPanelComandos1Layout.setHorizontalGroup(
            jPanelComandos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComandos1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrimeiro1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanelComandos1Layout.setVerticalGroup(
            jPanelComandos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComandos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComandos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonRestaurar)
                    .addComponent(jButtonPrimeiro1)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonIncluir.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelCadastro12Layout = new javax.swing.GroupLayout(jPanelCadastro12);
        jPanelCadastro12.setLayout(jPanelCadastro12Layout);
        jPanelCadastro12Layout.setHorizontalGroup(
            jPanelCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastro12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFichaCadastro12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelComandos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelCadastro12Layout.setVerticalGroup(
            jPanelCadastro12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastro12Layout.createSequentialGroup()
                .addComponent(jLabelHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFichaCadastro12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelComandos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPaneClientes12.addTab("Cadastro", jPanelCadastro12);

        jPanelParametro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Parâmetro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel183.setForeground(new java.awt.Color(102, 102, 102));
        jLabel183.setText("Nome do Filme");

        jButtonExecutaPesquisa.setMnemonic('E');
        jButtonExecutaPesquisa.setText("Consultar");
        jButtonExecutaPesquisa.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutaPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutaPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelParametroLayout = new javax.swing.GroupLayout(jPanelParametro);
        jPanelParametro.setLayout(jPanelParametroLayout);
        jPanelParametroLayout.setHorizontalGroup(
            jPanelParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametroLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel183)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldParametroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExecutaPesquisa)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelParametroLayout.setVerticalGroup(
            jPanelParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametroLayout.createSequentialGroup()
                .addGroup(jPanelParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel183)
                    .addComponent(jTextFieldParametroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExecutaPesquisa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelResposta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Consulta de Filmes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jTableFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(jTableFilmes);

        javax.swing.GroupLayout jPanelRespostaLayout = new javax.swing.GroupLayout(jPanelResposta);
        jPanelResposta.setLayout(jPanelRespostaLayout);
        jPanelRespostaLayout.setHorizontalGroup(
            jPanelRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRespostaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRespostaLayout.setVerticalGroup(
            jPanelRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRespostaLayout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelHora1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora1.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora1.setText("Hora");

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelResposta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelParametro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addComponent(jLabelHora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelResposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneClientes12.addTab("Pesquisa", jPanelConsulta);

        jPanelParametro2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Parâmetro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel185.setForeground(new java.awt.Color(102, 102, 102));
        jLabel185.setText("Nome do Filme");

        jButtonExecutaPesquisaAlugados.setMnemonic('E');
        jButtonExecutaPesquisaAlugados.setText("Consultar");
        jButtonExecutaPesquisaAlugados.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutaPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutaPesquisaAlugados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutaPesquisaAlugadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelParametro2Layout = new javax.swing.GroupLayout(jPanelParametro2);
        jPanelParametro2.setLayout(jPanelParametro2Layout);
        jPanelParametro2Layout.setHorizontalGroup(
            jPanelParametro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel185)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldParametroNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExecutaPesquisaAlugados)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelParametro2Layout.setVerticalGroup(
            jPanelParametro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro2Layout.createSequentialGroup()
                .addGroup(jPanelParametro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel185)
                    .addComponent(jTextFieldParametroNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExecutaPesquisaAlugados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelResposta3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Consulta de Filmes Alugados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jTableFilmes3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane13.setViewportView(jTableFilmes3);

        javax.swing.GroupLayout jPanelResposta3Layout = new javax.swing.GroupLayout(jPanelResposta3);
        jPanelResposta3.setLayout(jPanelResposta3Layout);
        jPanelResposta3Layout.setHorizontalGroup(
            jPanelResposta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResposta3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelResposta3Layout.setVerticalGroup(
            jPanelResposta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResposta3Layout.createSequentialGroup()
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelHora4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora4.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora4.setText("Hora");

        javax.swing.GroupLayout jPanelConsulta3Layout = new javax.swing.GroupLayout(jPanelConsulta3);
        jPanelConsulta3.setLayout(jPanelConsulta3Layout);
        jPanelConsulta3Layout.setHorizontalGroup(
            jPanelConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelResposta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelParametro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHora4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelConsulta3Layout.setVerticalGroup(
            jPanelConsulta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta3Layout.createSequentialGroup()
                .addComponent(jLabelHora4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParametro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelResposta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneClientes12.addTab("Consulta", jPanelConsulta3);

        jPanelResposta1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Relação com Estatística de Filmes por período de locação  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jTableFilmes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane11.setViewportView(jTableFilmes1);

        javax.swing.GroupLayout jPanelResposta1Layout = new javax.swing.GroupLayout(jPanelResposta1);
        jPanelResposta1.setLayout(jPanelResposta1Layout);
        jPanelResposta1Layout.setHorizontalGroup(
            jPanelResposta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResposta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelResposta1Layout.setVerticalGroup(
            jPanelResposta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResposta1Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelHora2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora2.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora2.setText("Hora");

        jPanelParametro4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Total Geral", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel186.setForeground(new java.awt.Color(102, 102, 102));
        jLabel186.setText("Locações:");

        jLabel187.setForeground(new java.awt.Color(102, 102, 102));
        jLabel187.setText("Valor:");

        jTextFieldParametroValue.setEditable(false);

        jTextFieldParametroLoc.setEditable(false);

        javax.swing.GroupLayout jPanelParametro4Layout = new javax.swing.GroupLayout(jPanelParametro4);
        jPanelParametro4.setLayout(jPanelParametro4Layout);
        jPanelParametro4Layout.setHorizontalGroup(
            jPanelParametro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelParametro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel186)
                    .addComponent(jLabel187))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelParametro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldParametroLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldParametroValue, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanelParametro4Layout.setVerticalGroup(
            jPanelParametro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro4Layout.createSequentialGroup()
                .addGroup(jPanelParametro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel186)
                    .addComponent(jTextFieldParametroLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelParametro4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel187)
                    .addComponent(jTextFieldParametroValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelParametro6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Parâmetro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel190.setForeground(new java.awt.Color(102, 102, 102));
        jLabel190.setText("Período");

        jButtonExecutarConsulta.setMnemonic('E');
        jButtonExecutarConsulta.setText("Consultar");
        jButtonExecutarConsulta.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutaPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarConsultaActionPerformed(evt);
            }
        });

        jLabel191.setForeground(new java.awt.Color(102, 102, 102));
        jLabel191.setText("à");

        javax.swing.GroupLayout jPanelParametro6Layout = new javax.swing.GroupLayout(jPanelParametro6);
        jPanelParametro6.setLayout(jPanelParametro6Layout);
        jPanelParametro6Layout.setHorizontalGroup(
            jPanelParametro6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel190)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldParametroData3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel191)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldParametroData4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButtonExecutarConsulta)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanelParametro6Layout.setVerticalGroup(
            jPanelParametro6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro6Layout.createSequentialGroup()
                .addGroup(jPanelParametro6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel190)
                    .addComponent(jLabel191)
                    .addComponent(jTextFieldParametroData4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldParametroData3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExecutarConsulta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelConsulta2Layout = new javax.swing.GroupLayout(jPanelConsulta2);
        jPanelConsulta2.setLayout(jPanelConsulta2Layout);
        jPanelConsulta2Layout.setHorizontalGroup(
            jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelParametro4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResposta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHora2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelParametro6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelConsulta2Layout.setVerticalGroup(
            jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta2Layout.createSequentialGroup()
                .addComponent(jLabelHora2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParametro6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelResposta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelParametro4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneClientes12.addTab("Estatística", jPanelConsulta2);

        jPanelParametro7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Relação de Filmes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jButtonExecutarRelatorio.setMnemonic('E');
        jButtonExecutarRelatorio.setText("Relatório");
        jButtonExecutarRelatorio.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutaPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelParametro7Layout = new javax.swing.GroupLayout(jPanelParametro7);
        jPanelParametro7.setLayout(jPanelParametro7Layout);
        jPanelParametro7Layout.setHorizontalGroup(
            jPanelParametro7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro7Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jButtonExecutarRelatorio)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanelParametro7Layout.setVerticalGroup(
            jPanelParametro7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro7Layout.createSequentialGroup()
                .addComponent(jButtonExecutarRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelHora3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora3.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora3.setText("Hora");

        javax.swing.GroupLayout jPanelConsulta4Layout = new javax.swing.GroupLayout(jPanelConsulta4);
        jPanelConsulta4.setLayout(jPanelConsulta4Layout);
        jPanelConsulta4Layout.setHorizontalGroup(
            jPanelConsulta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsulta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHora3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelParametro7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelConsulta4Layout.setVerticalGroup(
            jPanelConsulta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta4Layout.createSequentialGroup()
                .addComponent(jLabelHora3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParametro7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );

        jTabbedPaneClientes12.addTab("Relatório", jPanelConsulta4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabelClientes)
                .addGap(115, 115, 115)
                .addComponent(jLabelFilmes)
                .addGap(116, 116, 116)
                .addComponent(jLabelLocacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jLabel3D)
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3D, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPaneClientes12, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3D, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonLocacao)
                        .addComponent(jButtonFilmes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientes)
                    .addComponent(jLabelFilmes)
                    .addComponent(jLabelLocacao)
                    .addComponent(jLabel3D))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPaneClientes12, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuArquivo.setText("Arquivo");

        jMenuItemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/button_cancel.png"))); // NOI18N
        jMenuItemFechar.setText("Fechar");
        jMenuItemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFecharActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemFechar);

        jMenuBar1.add(jMenuArquivo);

        jMenuTemas.setText("Temas");
        jMenuBar1.add(jMenuTemas);

        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre o aplicativo...");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        utilitarios.UsarSustance.substanceLtpUtil(jMenuTemas);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        new jDialogSobre(this, true);
}//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFecharActionPerformed
        fechar();
}//GEN-LAST:event_jMenuItemFecharActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        JFrameClientes JF_Clientes = new JFrameClientes();
        JF_Clientes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilmesActionPerformed
        JFrameLocadora J_Loc = new JFrameLocadora();
        J_Loc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFilmesActionPerformed

    private void jButtonLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocacaoActionPerformed
        JFrameLocar JF_Locar = new JFrameLocar();
        JF_Locar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLocacaoActionPerformed

    private void jButton3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3DActionPerformed
        JFrame3D JF_3D = new JFrame3D(this, true);
        JF_3D.setVisible(true);
    }//GEN-LAST:event_jButton3DActionPerformed

    private void jButtonExecutarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarConsultaActionPerformed
        try {
            if (!LtpUtil.validarData(jTextFieldParametroData3.getText()) || !LtpUtil.validarData(jTextFieldParametroData4.getText())) {
                JOptionPane.showMessageDialog(
                        this,
                        "Data Inválida",
                        "Consulta de Filmes pelo Período",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            DateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
            String as = jTextFieldParametroData3.getText();
            java.util.Date parsedUtilDate = formater.parse(as);
            java.sql.Date sqltDate = new java.sql.Date(parsedUtilDate.getTime());

            DateFormat formater2 = new SimpleDateFormat("dd/MM/yyyy");
            String as2 = jTextFieldParametroData4.getText();
            java.util.Date parsedUtilDate2 = formater2.parse(as2);
            java.sql.Date sqltDate2 = new java.sql.Date(parsedUtilDate2.getTime());

            jScrollPane11.setViewportView(m_loc.buscarFilmesPorPeriodo(sqltDate, sqltDate2));

            ResultSet rs = m_loc.buscarTotalLocacao(sqltDate, sqltDate2);
            jTextFieldParametroLoc.setText(rs.getString("TOTAL_LOCACOES"));
            jTextFieldParametroValue.setText(rs.getString("TOTAL_VALOR"));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Consulta de Filmes pelo Período",
                    JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_jButtonExecutarConsultaActionPerformed

    private void jButtonExecutaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutaPesquisaActionPerformed
        /*Vector<Filme> listaFilmes = null;
        try {
        jTable1.setsetText("");
        listaFilmes = m_loc.buscarFilmesPorNome(jTextFieldParametroNome.getText().trim());
        for (Filme objFilme : listaFilmes) {
        jTable1.append(objFilme.toString() + "\n");
        }
        jTable1.append("Nº de Filmes encontrados: " + listaFilmes.size() + "\n");
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(),
        "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
        }*/
        try {
            jScrollPane10.setViewportView(m_loc.buscarFilmesPorNome(jTextFieldParametroNome.getText()));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Consulta de Filmes pelo Nome",
                    JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_jButtonExecutaPesquisaActionPerformed

    private void jButtonPrimeiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiro1ActionPerformed
        limparForm();
}//GEN-LAST:event_jButtonPrimeiro1ActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        fechar();
}//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        String codigo = JOptionPane.showInputDialog(this, "Informe o código do filme", "Cadastro de Filmes", JOptionPane.QUESTION_MESSAGE);
        if (codigo == null || !codigo.matches("[0-9]*") || codigo.equals("")) {
            return;
        }
        exibirFilmeCodigo(Integer.parseInt(codigo));
}//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaurarActionPerformed
        if (jTextFieldCodigo.getText() == null || jTextFieldCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo código vazio.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jTextFieldCodigo.requestFocus();
            return;
        }
        exibirFilmeCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
}//GEN-LAST:event_jButtonRestaurarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if (validarAtualizacao() == false) {
            return;
        }
        if (jTextFieldCodigo.getText() == null || jTextFieldCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo código vazio.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jTextFieldCodigo.requestFocus();
            return;
        }
        try {
            DateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
            String data = jFormattedTextFieldData.getText();
            java.util.Date parsedUtilDate = formater.parse(data);
            java.sql.Date sqltDate = new java.sql.Date(parsedUtilDate.getTime());

            int cod = Integer.parseInt(jTextFieldCodigo.getText());
            String nome = jFormattedTextFieldBrasil.getText();
            String nomeOriginal = jFormattedTextFieldOriginal.getText();
            int ano = Integer.parseInt(jFormattedTextFieldAno.getText());
            String genero = jFormattedTextFieldGenero.getText();
            String ator = jFormattedTextFieldAtor.getText();
            float pontos = Float.parseFloat(jFormattedTextFieldPontos.getText());
            int votos = Integer.parseInt(jFormattedTextFieldVotos.getText());
            String resumo = jFormattedTextFieldResumo.getText();
            int tempo = Integer.parseInt(jFormattedTextFieldTempo.getText());
            int estoque = Integer.parseInt(jFormattedTextFieldEstoque.getText());
            int emprestado = Integer.parseInt(jFormattedTextFieldEmprestado.getText());
            double valor = Double.parseDouble(jFormattedTextFieldDiaria.getText());

            m_loc.alterarFilme(new Filme(cod, nome,
                    nomeOriginal, ano,
                    genero, ator, pontos, votos, resumo, tempo, estoque, emprestado, valor, sqltDate));
            JOptionPane.showMessageDialog(this, "Filme Alterado.",
                    "Cadastro de Filmes", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                    "Cadastro de Filmes", JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTextFieldCodigo.getText().equals("") || jTextFieldCodigo == null) {
            return;
        }
        if (JOptionPane.showConfirmDialog(null, "Confirmar a exclusão do filme - "
                + jFormattedTextFieldBrasil.getText().trim() + "?",
                "Cadastro de Filme",
                JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            m_loc.excluirFilme(Integer.parseInt(jTextFieldCodigo.getText()));
            JOptionPane.showMessageDialog(this, "Filme Excluído.",
                    "Cadastro de Filmes", JOptionPane.INFORMATION_MESSAGE);
            limparForm();

        } catch (SQLException objErro) {
            JOptionPane.showMessageDialog(this, objErro.getMessage(),
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);

        }
}//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        if (validarAtualizacao() == false) {
            return;
        }
        int codigo;
        try {
            codigo = (m_loc.buscarFilmeUltimo().getCodigo()) + 1;
        } catch (Exception ex) {
            codigo = 1;
        }

        try {
            DateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
            String data = jFormattedTextFieldData.getText();
            java.util.Date parsedUtilDate = formater.parse(data);
            java.sql.Date sqltDate = new java.sql.Date(parsedUtilDate.getTime());

            String nome = jFormattedTextFieldBrasil.getText();
            String nomeOriginal = jFormattedTextFieldOriginal.getText();
            int ano = Integer.parseInt(jFormattedTextFieldAno.getText());
            String genero = jFormattedTextFieldGenero.getText();
            String ator = jFormattedTextFieldAtor.getText();
            float pontos = Float.parseFloat(jFormattedTextFieldPontos.getText());
            int votos = Integer.parseInt(jFormattedTextFieldVotos.getText());
            String resumo = jFormattedTextFieldResumo.getText();
            int tempo = Integer.parseInt(jFormattedTextFieldTempo.getText());
            int estoque = Integer.parseInt(jFormattedTextFieldEstoque.getText());
            int emprestado = Integer.parseInt(jFormattedTextFieldEmprestado.getText());
            double valor = Double.parseDouble(jFormattedTextFieldDiaria.getText());

            m_loc.adicionarFilme(new Filme(codigo, nome,
                    nomeOriginal, ano,
                    genero, ator, pontos, votos, resumo, tempo, estoque, emprestado, valor, sqltDate));

            JOptionPane.showMessageDialog(this, "Filme Cadastrado.",
                    "Cadastro de Filmes", JOptionPane.INFORMATION_MESSAGE);
            limparForm();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                    "Cadastro de Filmes", JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        ultimo();
}//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        proximo();
}//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        anterior();
}//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        primeiro();
}//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonExecutarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarRelatorioActionPerformed
        HashMap<String,Object> parametros = new HashMap<String, Object>();
        parametros.put("", "");
        parametros.put("", "");
        try {
            LtpUtil.gerarRelatorio(
                    LtpUtil.RELATORIO_VISUALIZADOR_JASPER,
                    bdlocadora.BDLocadora.objCon,
                    parametros,
                    getClass().getResource("relatorios/Relatorio_F.jasper").openStream(),
                    "Relação com Estatísticas de Filmes");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExecutarRelatorioActionPerformed

    private void jButtonExecutaPesquisaAlugadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutaPesquisaAlugadosActionPerformed
         try {
            jScrollPane13.setViewportView(m_loc.buscarFilmesAlugadosPorNome(jTextFieldParametroNome.getText()));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Consulta de Filmes Alugados pelo Nome",
                    JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_jButtonExecutaPesquisaAlugadosActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3D;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExecutaPesquisa;
    private javax.swing.JButton jButtonExecutaPesquisaAlugados;
    private javax.swing.JButton jButtonExecutarConsulta;
    private javax.swing.JButton jButtonExecutarRelatorio;
    private javax.swing.JButton jButtonFilmes;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLocacao;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonPrimeiro1;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonRestaurar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JFormattedTextField jFormattedTextFieldAno;
    private javax.swing.JFormattedTextField jFormattedTextFieldAtor;
    private javax.swing.JFormattedTextField jFormattedTextFieldBrasil;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldDiaria;
    private javax.swing.JFormattedTextField jFormattedTextFieldEmprestado;
    private javax.swing.JFormattedTextField jFormattedTextFieldEstoque;
    private javax.swing.JFormattedTextField jFormattedTextFieldGenero;
    private javax.swing.JFormattedTextField jFormattedTextFieldOriginal;
    private javax.swing.JFormattedTextField jFormattedTextFieldPontos;
    private javax.swing.JTextArea jFormattedTextFieldResumo;
    private javax.swing.JFormattedTextField jFormattedTextFieldTempo;
    private javax.swing.JFormattedTextField jFormattedTextFieldVotos;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel3D;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelFilmes;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelHora1;
    private javax.swing.JLabel jLabelHora2;
    private javax.swing.JLabel jLabelHora3;
    private javax.swing.JLabel jLabelHora4;
    private javax.swing.JLabel jLabelLocacao;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemFechar;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuTemas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastro12;
    private javax.swing.JPanel jPanelComandos1;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelConsulta2;
    private javax.swing.JPanel jPanelConsulta3;
    private javax.swing.JPanel jPanelConsulta4;
    private javax.swing.JPanel jPanelFichaCadastro12;
    private javax.swing.JPanel jPanelParametro;
    private javax.swing.JPanel jPanelParametro2;
    private javax.swing.JPanel jPanelParametro4;
    private javax.swing.JPanel jPanelParametro6;
    private javax.swing.JPanel jPanelParametro7;
    private javax.swing.JPanel jPanelResposta;
    private javax.swing.JPanel jPanelResposta1;
    private javax.swing.JPanel jPanelResposta3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPaneResumo;
    private javax.swing.JTabbedPane jTabbedPaneClientes12;
    private javax.swing.JTable jTableFilmes;
    private javax.swing.JTable jTableFilmes1;
    private javax.swing.JTable jTableFilmes3;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldParametroData3;
    private javax.swing.JTextField jTextFieldParametroData4;
    private javax.swing.JTextField jTextFieldParametroLoc;
    private javax.swing.JTextField jTextFieldParametroNome;
    private javax.swing.JTextField jTextFieldParametroNome2;
    private javax.swing.JTextField jTextFieldParametroValue;
    // End of variables declaration//GEN-END:variables

    private void fechar() {
        if (JOptionPane.showConfirmDialog(
                this,
                "Confirma a saída?",
                "Locadora",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            try {
                bdlocadora.BDLocadora.fecharConexao();
                dispose();
                System.exit(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                System.exit(1);
            }

        }
    }

    private void primeiro() {
        try {
            exibirFilme(m_loc.buscarFilmePrimeiro());
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Filme", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void anterior() {
        try {
            if (jTextFieldCodigo.getText().equals("") || jTextFieldCodigo == null) {
                primeiro();
                return;
            }
            exibirFilme(m_loc.buscarFilmeAnterior(Integer.parseInt(jTextFieldCodigo.getText())));
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void proximo() {
        try {
            if (jTextFieldCodigo.getText().equals("") || jTextFieldCodigo == null) {
                primeiro();
                return;
            }
            exibirFilme(m_loc.buscarFilmeProximo(Integer.parseInt(jTextFieldCodigo.getText())));
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void ultimo() {
        try {
            exibirFilme(m_loc.buscarFilmeUltimo());
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void exibirFilmeCodigo(int codigo) {
        try {
            exibirFilme(m_loc.buscarFilmePorCodigo(codigo));
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void exibirFilme(Filme objFilme) {
        jTextFieldCodigo.setText(String.valueOf(objFilme.getCodigo()));
        jFormattedTextFieldBrasil.setText(objFilme.getNomeBrasil().trim());
        jFormattedTextFieldOriginal.setText(objFilme.getNomeOriginal().trim());
        jFormattedTextFieldAno.setText(String.valueOf(objFilme.getAno()));
        jFormattedTextFieldGenero.setText(objFilme.getGenero().trim());
        jFormattedTextFieldAtor.setText(objFilme.getAtor().trim());
        jFormattedTextFieldPontos.setText(String.valueOf(objFilme.getPontos()));
        jFormattedTextFieldVotos.setText(String.valueOf(objFilme.getVotos()));
        jFormattedTextFieldResumo.setText(objFilme.getResumo().trim());
        jFormattedTextFieldTempo.setText(String.valueOf(objFilme.getTempo()));
        jFormattedTextFieldEstoque.setText(String.valueOf(objFilme.getEstoque()));
        jFormattedTextFieldEmprestado.setText(String.valueOf(objFilme.getEmprestado()));
        jFormattedTextFieldDiaria.setText(String.valueOf(objFilme.getValor()));
        jFormattedTextFieldData.setText(LtpUtil.formatarData(objFilme.getData(), "dd/MM/yyyy"));

    }

    private void limparForm() {
        jTextFieldCodigo.setText("");
        jFormattedTextFieldBrasil.setText("");
        jFormattedTextFieldOriginal.setText("");
        jFormattedTextFieldAno.setText("");
        jFormattedTextFieldGenero.setText("");
        jFormattedTextFieldAtor.setText("");
        jFormattedTextFieldPontos.setText("");
        jFormattedTextFieldVotos.setText("");
        jFormattedTextFieldResumo.setText("");
        jFormattedTextFieldTempo.setText("");
        jFormattedTextFieldEstoque.setText("");
        jFormattedTextFieldEmprestado.setText("");
        jFormattedTextFieldDiaria.setText("");
        jFormattedTextFieldData.setText("");
    }

    private boolean validarAtualizacao() {

        if (jFormattedTextFieldBrasil.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta informar o nome no brasil do filme.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldBrasil.requestFocus();
            return false;
        }
        if (jFormattedTextFieldOriginal.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta informar o nome original do filme.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldOriginal.requestFocus();
            return false;
        }
        if (jFormattedTextFieldAno.getText().trim().equals("") || !jFormattedTextFieldAno.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(this, "Ano Inválido.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldAno.requestFocus();
            return false;
        }
        if (jFormattedTextFieldGenero.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta informar o Gênero Principal do filme.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldGenero.requestFocus();
            return false;
        }
        if (jFormattedTextFieldAtor.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta informar o Ator Principal do filme.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldAtor.requestFocus();
            return false;
        }
        if (jFormattedTextFieldPontos.getText().trim().equals("") || !isFloat(jFormattedTextFieldPontos.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Pontuação IMDB Inválida.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldPontos.requestFocus();
            return false;
        }
        if (jFormattedTextFieldVotos.getText().trim().equals("") || !jFormattedTextFieldVotos.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(this, "Votos IMDB Inválidos.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldVotos.requestFocus();
            return false;
        }
        if (jFormattedTextFieldResumo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta informar o Resumo IMDB do filme.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldResumo.requestFocus();
            return false;
        }
        if (jFormattedTextFieldTempo.getText().trim().equals("") || !jFormattedTextFieldTempo.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(this, "Tempo Inválido.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldTempo.requestFocus();
            return false;
        }
        if (jFormattedTextFieldEstoque.getText().trim().equals("") || !jFormattedTextFieldEstoque.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(this, "Estoque Inválido.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldEstoque.requestFocus();
            return false;
        }
        if (jFormattedTextFieldEmprestado.getText().trim().equals("") || !jFormattedTextFieldEmprestado.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(this, "Filmes emprestados inválidos.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldEmprestado.requestFocus();
            return false;
        }
        if (jFormattedTextFieldDiaria.getText().trim().equals("") || !isDouble(jFormattedTextFieldEmprestado.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Valor da diária inválido.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldDiaria.requestFocus();
            return false;
        }
        if (!jFormattedTextFieldData.getText().trim().equals("")
                && !LtpUtil.validarData(jFormattedTextFieldData.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Data Inválida.",
                    "Cadastro de Filmes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldData.requestFocus();
            return false;
        }
        return true;
    }

    public boolean isDouble(String str) {
        try {
            Double.parseDouble(str);
        } catch (Exception e) {
            return false;
        }
        return true;
    }

    public boolean isFloat(String str) {
        try {
            Float.parseFloat(str);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
}
