/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameLocadora.java
 *
 * Created on 26/10/2011, 22:54:06
 */
package usuario;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utilitarios.LtpUtil;
import dados.Cliente;
import locnegocio.LocNegocio;
import java.text.DateFormat;
import java.util.GregorianCalendar;
import java.util.HashMap;

/**
 *
 * @author JP
 */
public class JFrameClientes extends javax.swing.JFrame {

    //Member
    private static LocNegocio m_loc = new LocNegocio();

    /** Creates new form JFrameClintes */
    public JFrameClientes() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon icone = new ImageIcon(getClass().getResource("recursos/switchuser.png"));
        setIconImage(icone.getImage());
        setVisible(true);
        jFormattedTextFieldNome.requestFocus();
        Thread horario = new Thread(new Runnable() {

            public void run() {
                while (true) {
                    jLabelHora.setText(new SimpleDateFormat("HH:mm:ss").format(new GregorianCalendar().getTime()));
                    jLabelHora1.setText(jLabelHora.getText());
                    jLabelHora2.setText(jLabelHora.getText());
                    jLabelHora3.setText(jLabelHora.getText());
                    jLabelHora4.setText(jLabelHora.getText());
                    try {
                        Thread.sleep(1000); // Interromper por 1000 milisegundos
                    } catch (InterruptedException e) {
                    }
                }
            }
        });
        horario.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonClientes = new javax.swing.JButton();
        jButtonFilmes = new javax.swing.JButton();
        jButtonLocacao = new javax.swing.JButton();
        jButton3D = new javax.swing.JButton();
        jLabelClientes = new javax.swing.JLabel();
        jLabelFilmes = new javax.swing.JLabel();
        jLabelLocacao = new javax.swing.JLabel();
        jLabel3D = new javax.swing.JLabel();
        jTabbedPaneClientes = new javax.swing.JTabbedPane();
        jPanelCadastro = new javax.swing.JPanel();
        jPanelFichaCadastro = new javax.swing.JPanel();
        jFormattedTextFieldNome = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextFieldEmail = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jPanelComandos = new javax.swing.JPanel();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonRestaurar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonPrimeiro1 = new javax.swing.JButton();
        jLabelHora = new javax.swing.JLabel();
        jPanelConsulta = new javax.swing.JPanel();
        jPanelParametro = new javax.swing.JPanel();
        jTextFieldParametroNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonExecutarPesquisa = new javax.swing.JButton();
        jPanelResposta = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabelHora1 = new javax.swing.JLabel();
        jPanelCadastro2 = new javax.swing.JPanel();
        jLabelHora2 = new javax.swing.JLabel();
        jPanelParametro1 = new javax.swing.JPanel();
        jTextFieldParametroData1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonExecutarConsulta = new javax.swing.JButton();
        jTextFieldParametroData2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldParametroNome1 = new javax.swing.JTextField();
        jLabel183 = new javax.swing.JLabel();
        jPanelResposta1 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTableClientes1 = new javax.swing.JTable();
        jPanelConsulta1 = new javax.swing.JPanel();
        jPanelParametro2 = new javax.swing.JPanel();
        jLabel184 = new javax.swing.JLabel();
        jButtonExecutarRelatorio = new javax.swing.JButton();
        jTextFieldParametrofim = new javax.swing.JTextField();
        jTextFieldParametroinicio = new javax.swing.JTextField();
        jLabel185 = new javax.swing.JLabel();
        jLabelHora3 = new javax.swing.JLabel();
        jPanelConsulta2 = new javax.swing.JPanel();
        jPanelParametro3 = new javax.swing.JPanel();
        jLabel186 = new javax.swing.JLabel();
        jButtonExecutarRelatorioProva = new javax.swing.JButton();
        jTextFieldParametroAno = new javax.swing.JTextField();
        jTextFieldParametroMes = new javax.swing.JTextField();
        jLabel187 = new javax.swing.JLabel();
        jLabelHora4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemFechar = new javax.swing.JMenuItem();
        jMenuTemas = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Locadora LTDA - Clientes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(233, 233, 247));

        jButtonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/User-Clients-icon.png"))); // NOI18N
        jButtonClientes.setFocusPainted(false);
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonFilmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/Movies-icon.png"))); // NOI18N
        jButtonFilmes.setFocusPainted(false);
        jButtonFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilmesActionPerformed(evt);
            }
        });

        jButtonLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/Film-Maker-Male-Light-icon.png"))); // NOI18N
        jButtonLocacao.setFocusPainted(false);
        jButtonLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocacaoActionPerformed(evt);
            }
        });

        jButton3D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/3D-Penguins-icon.png"))); // NOI18N
        jButton3D.setFocusPainted(false);
        jButton3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3DActionPerformed(evt);
            }
        });

        jLabelClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelClientes.setForeground(new java.awt.Color(153, 153, 153));
        jLabelClientes.setText("Clientes");

        jLabelFilmes.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelFilmes.setForeground(new java.awt.Color(153, 153, 153));
        jLabelFilmes.setText("Filmes");

        jLabelLocacao.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabelLocacao.setForeground(new java.awt.Color(153, 153, 153));
        jLabelLocacao.setText("Locação");

        jLabel3D.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
        jLabel3D.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3D.setText("3D");

        jPanelFichaCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Ficha de Cadastro de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Código");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nome");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Telefone");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("E-Mail");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("CPF");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Data");

        jTextFieldCodigo.setEditable(false);

        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("dd/MM/yyyy");

        javax.swing.GroupLayout jPanelFichaCadastroLayout = new javax.swing.GroupLayout(jPanelFichaCadastro);
        jPanelFichaCadastro.setLayout(jPanelFichaCadastroLayout);
        jPanelFichaCadastroLayout.setHorizontalGroup(
            jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(33, 33, 33)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jFormattedTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldCPF)
                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextFieldEmail)
                        .addGroup(jPanelFichaCadastroLayout.createSequentialGroup()
                            .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)))
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanelFichaCadastroLayout.setVerticalGroup(
            jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelComandos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Comandos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 51))); // NOI18N

        jButtonPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/primeiro.gif"))); // NOI18N
        jButtonPrimeiro.setToolTipText("Primeiro");
        jButtonPrimeiro.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/anterior.gif"))); // NOI18N
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/proximo.gif"))); // NOI18N
        jButtonProximo.setToolTipText("Próximo");
        jButtonProximo.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/ultimo.gif"))); // NOI18N
        jButtonUltimo.setToolTipText("Último");
        jButtonUltimo.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/inserir.gif"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/remover.gif"))); // NOI18N
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/editar.gif"))); // NOI18N
        jButtonEditar.setToolTipText("Alterar");
        jButtonEditar.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonRestaurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/atualizar.gif"))); // NOI18N
        jButtonRestaurar.setToolTipText("Restaurar");
        jButtonRestaurar.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaurarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/buscar.gif"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar");
        jButtonPesquisar.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/fexit.gif"))); // NOI18N
        jButtonSair.setToolTipText("Fechar");
        jButtonSair.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonPrimeiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/broom.gif"))); // NOI18N
        jButtonPrimeiro1.setToolTipText("Limpar");
        jButtonPrimeiro.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPrimeiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiro1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelComandosLayout = new javax.swing.GroupLayout(jPanelComandos);
        jPanelComandos.setLayout(jPanelComandosLayout);
        jPanelComandosLayout.setHorizontalGroup(
            jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComandosLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRestaurar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPrimeiro1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanelComandosLayout.setVerticalGroup(
            jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelComandosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelComandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonRestaurar)
                    .addComponent(jButtonPrimeiro1)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonIncluir.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));

        jLabelHora.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora.setText("Hora");

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelFichaCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelComandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addComponent(jLabelHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFichaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelComandos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPaneClientes.addTab("Cadastro", jPanelCadastro);

        jPanelParametro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Parâmetro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Nome do Cliente");

        jButtonExecutarPesquisa.setMnemonic('E');
        jButtonExecutarPesquisa.setText("Consultar");
        jButtonExecutarPesquisa.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutarPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutarPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelParametroLayout = new javax.swing.GroupLayout(jPanelParametro);
        jPanelParametro.setLayout(jPanelParametroLayout);
        jPanelParametroLayout.setHorizontalGroup(
            jPanelParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametroLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldParametroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExecutarPesquisa)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelParametroLayout.setVerticalGroup(
            jPanelParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametroLayout.createSequentialGroup()
                .addGroup(jPanelParametroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldParametroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExecutarPesquisa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelResposta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Pesquisa aproximada pelo nome do cliente ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(jTableClientes);

        javax.swing.GroupLayout jPanelRespostaLayout = new javax.swing.GroupLayout(jPanelResposta);
        jPanelResposta.setLayout(jPanelRespostaLayout);
        jPanelRespostaLayout.setHorizontalGroup(
            jPanelRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRespostaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRespostaLayout.setVerticalGroup(
            jPanelRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRespostaLayout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelHora1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora1.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora1.setText("Hora");

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelParametro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHora1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addComponent(jLabelHora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneClientes.addTab("Pesquisa", jPanelConsulta);

        jLabelHora2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora2.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora2.setText("Hora");

        jPanelParametro1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Parâmetro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Período");

        jButtonExecutarConsulta.setMnemonic('E');
        jButtonExecutarConsulta.setText("Consultar");
        jButtonExecutarConsulta.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutarPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarConsultaActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("à");

        jLabel183.setForeground(new java.awt.Color(102, 102, 102));
        jLabel183.setText("Nome do Cliente");

        javax.swing.GroupLayout jPanelParametro1Layout = new javax.swing.GroupLayout(jPanelParametro1);
        jPanelParametro1.setLayout(jPanelParametro1Layout);
        jPanelParametro1Layout.setHorizontalGroup(
            jPanelParametro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanelParametro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel183)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanelParametro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelParametro1Layout.createSequentialGroup()
                        .addComponent(jTextFieldParametroData1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldParametroData2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldParametroNome1))
                .addGap(53, 53, 53)
                .addComponent(jButtonExecutarConsulta)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanelParametro1Layout.setVerticalGroup(
            jPanelParametro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro1Layout.createSequentialGroup()
                .addGroup(jPanelParametro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParametro1Layout.createSequentialGroup()
                        .addGroup(jPanelParametro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel183)
                            .addComponent(jTextFieldParametroNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanelParametro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldParametroData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldParametroData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelParametro1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButtonExecutarConsulta)))
                .addContainerGap())
        );

        jPanelResposta1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Consulta de clientes que alugaram filmes por período de locação ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jTableClientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane11.setViewportView(jTableClientes1);

        javax.swing.GroupLayout jPanelResposta1Layout = new javax.swing.GroupLayout(jPanelResposta1);
        jPanelResposta1.setLayout(jPanelResposta1Layout);
        jPanelResposta1Layout.setHorizontalGroup(
            jPanelResposta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResposta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelResposta1Layout.setVerticalGroup(
            jPanelResposta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResposta1Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelCadastro2Layout = new javax.swing.GroupLayout(jPanelCadastro2);
        jPanelCadastro2.setLayout(jPanelCadastro2Layout);
        jPanelCadastro2Layout.setHorizontalGroup(
            jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastro2Layout.createSequentialGroup()
                .addContainerGap(573, Short.MAX_VALUE)
                .addComponent(jLabelHora2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCadastro2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelResposta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelParametro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanelCadastro2Layout.setVerticalGroup(
            jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastro2Layout.createSequentialGroup()
                .addComponent(jLabelHora2)
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(jPanelCadastro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCadastro2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jPanelParametro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanelResposta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );

        jTabbedPaneClientes.addTab("Consulta", jPanelCadastro2);

        jPanelParametro2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Parâmetro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel184.setForeground(new java.awt.Color(102, 102, 102));
        jLabel184.setText("Período");

        jButtonExecutarRelatorio.setMnemonic('E');
        jButtonExecutarRelatorio.setText("Relatório");
        jButtonExecutarRelatorio.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutarPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarRelatorioActionPerformed(evt);
            }
        });

        jLabel185.setForeground(new java.awt.Color(102, 102, 102));
        jLabel185.setText("à");

        javax.swing.GroupLayout jPanelParametro2Layout = new javax.swing.GroupLayout(jPanelParametro2);
        jPanelParametro2.setLayout(jPanelParametro2Layout);
        jPanelParametro2Layout.setHorizontalGroup(
            jPanelParametro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel184)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldParametroinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel185)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldParametrofim, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButtonExecutarRelatorio)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanelParametro2Layout.setVerticalGroup(
            jPanelParametro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro2Layout.createSequentialGroup()
                .addGroup(jPanelParametro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel184)
                    .addComponent(jLabel185)
                    .addComponent(jTextFieldParametrofim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldParametroinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExecutarRelatorio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelHora3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelHora3.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora3.setText("Hora");

        javax.swing.GroupLayout jPanelConsulta1Layout = new javax.swing.GroupLayout(jPanelConsulta1);
        jPanelConsulta1.setLayout(jPanelConsulta1Layout);
        jPanelConsulta1Layout.setHorizontalGroup(
            jPanelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsulta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelParametro2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHora3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelConsulta1Layout.setVerticalGroup(
            jPanelConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta1Layout.createSequentialGroup()
                .addComponent(jLabelHora3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParametro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jTabbedPaneClientes.addTab("Relatório", jPanelConsulta1);

        jPanelParametro3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Parâmetro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel186.setForeground(new java.awt.Color(102, 102, 102));
        jLabel186.setText("Mês");

        jButtonExecutarRelatorioProva.setMnemonic('E');
        jButtonExecutarRelatorioProva.setText("Relatório");
        jButtonExecutarRelatorioProva.setToolTipText("Executar pesquisa pelo nome");
        jButtonExecutarPesquisa.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExecutarRelatorioProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarRelatorioProvaActionPerformed(evt);
            }
        });

        jLabel187.setForeground(new java.awt.Color(102, 102, 102));
        jLabel187.setText("Ano");

        javax.swing.GroupLayout jPanelParametro3Layout = new javax.swing.GroupLayout(jPanelParametro3);
        jPanelParametro3.setLayout(jPanelParametro3Layout);
        jPanelParametro3Layout.setHorizontalGroup(
            jPanelParametro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel186)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldParametroMes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel187)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldParametroAno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonExecutarRelatorioProva)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanelParametro3Layout.setVerticalGroup(
            jPanelParametro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParametro3Layout.createSequentialGroup()
                .addGroup(jPanelParametro3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel186)
                    .addComponent(jTextFieldParametroMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel187)
                    .addComponent(jButtonExecutarRelatorioProva)
                    .addComponent(jTextFieldParametroAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelHora4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelHora4.setForeground(new java.awt.Color(0, 0, 255));
        jLabelHora4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelHora4.setText("Hora");

        javax.swing.GroupLayout jPanelConsulta2Layout = new javax.swing.GroupLayout(jPanelConsulta2);
        jPanelConsulta2.setLayout(jPanelConsulta2Layout);
        jPanelConsulta2Layout.setHorizontalGroup(
            jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsulta2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelParametro3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelHora4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelConsulta2Layout.setVerticalGroup(
            jPanelConsulta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsulta2Layout.createSequentialGroup()
                .addComponent(jLabelHora4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelParametro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jTabbedPaneClientes.addTab("Prova", jPanelConsulta2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabelClientes)
                .addGap(115, 115, 115)
                .addComponent(jLabelFilmes)
                .addGap(116, 116, 116)
                .addComponent(jLabelLocacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jLabel3D)
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3D, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPaneClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClientes)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton3D, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonLocacao)
                        .addComponent(jButtonFilmes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClientes)
                    .addComponent(jLabelFilmes)
                    .addComponent(jLabelLocacao)
                    .addComponent(jLabel3D))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPaneClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuArquivo.setText("Arquivo");

        jMenuItemFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/button_cancel.png"))); // NOI18N
        jMenuItemFechar.setText("Fechar");
        jMenuItemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFecharActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemFechar);

        jMenuBar1.add(jMenuArquivo);

        jMenuTemas.setText("Temas");
        jMenuBar1.add(jMenuTemas);

        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre o aplicativo...");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fechar();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        utilitarios.UsarSustance.substanceLtpUtil(jMenuTemas);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        new jDialogSobre(this, true);
}//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFecharActionPerformed
        fechar();
}//GEN-LAST:event_jMenuItemFecharActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        JFrameLocadora JF_Loc = new JFrameLocadora();
        JF_Loc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        primeiro();
}//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        anterior();
}//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        proximo();
}//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        ultimo();
}//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        if (validarAtualizacao() == false) {
            return;
        }
        if (!jTextFieldCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Cliente já existe.",
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
            jTextFieldCodigo.requestFocus();
            return;
        }
        int codigo;
        try {
            codigo = (m_loc.buscarClienteUltimo().getCodigo()) + 1;
        } catch (Exception ex) {
            codigo = 1;
        }

        try {
            DateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
            String as = jFormattedTextFieldData.getText();
            java.util.Date parsedUtilDate = formater.parse(as);
            java.sql.Date sqltDate = new java.sql.Date(parsedUtilDate.getTime());
            String nome = jFormattedTextFieldNome.getText();
            String CPF = jFormattedTextFieldCPF.getText();
            String Tel = jFormattedTextFieldTelefone.getText();
            String email = jFormattedTextFieldEmail.getText();

            m_loc.adicionarCliente(new Cliente(codigo, nome,
                    CPF, Tel,
                    email, sqltDate));
            JOptionPane.showMessageDialog(this, "Cliente Cadastrado.",
                    "Cadastro de Clientes", JOptionPane.INFORMATION_MESSAGE);
            limparForm();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                    "Cadastro de Clientes", JOptionPane.INFORMATION_MESSAGE);
        }

}//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTextFieldCodigo.getText().equals("") || jTextFieldCodigo == null) {
            return;
        }
        if (JOptionPane.showConfirmDialog(this, "Confirmar a exclusão do cliente - "
                + jFormattedTextFieldNome.getText().trim() + "?",
                "Cadastro de Clientes",
                JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            m_loc.excluirCliente(Integer.parseInt(jTextFieldCodigo.getText()));
            JOptionPane.showMessageDialog(this, "Cliente Excluído.",
                    "Cadastro de Clientes", JOptionPane.INFORMATION_MESSAGE);
            limparForm();

        } catch (SQLException objErro) {
            JOptionPane.showMessageDialog(this, objErro.getMessage(),
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);

        }
}//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if (validarAtualizacao() == false) {
            return;
        }
        if (jTextFieldCodigo.getText() == null || jTextFieldCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo código vazio.",
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
            jTextFieldCodigo.requestFocus();
            return;
        }
        try {
            DateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
            String as = jFormattedTextFieldData.getText();
            java.util.Date parsedUtilDate = formater.parse(as);
            java.sql.Date sqltDate = new java.sql.Date(parsedUtilDate.getTime());
            String nome = jFormattedTextFieldNome.getText();
            String CPF = jFormattedTextFieldCPF.getText();
            String Tel = jFormattedTextFieldTelefone.getText();
            String email = jFormattedTextFieldEmail.getText();
            int cod = Integer.parseInt(jTextFieldCodigo.getText());

            m_loc.alterarCliente(new Cliente(cod, nome,
                    CPF, Tel,
                    email, sqltDate));
            JOptionPane.showMessageDialog(this, "Cliente Alterado.",
                    "Cadastro de Clientes", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage(),
                    "Cadastro de Clientes", JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaurarActionPerformed
        if (jTextFieldCodigo.getText() == null || jTextFieldCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo código vazio.",
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
            return;
        }
        exibirClienteCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
}//GEN-LAST:event_jButtonRestaurarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        String codigo = JOptionPane.showInputDialog(this, "Informe o código do cliente", "Cadastro de Clientes", JOptionPane.QUESTION_MESSAGE);
        if (codigo == null || !codigo.matches("[0-9]*") || codigo.equals("")) {
            return;
        }
        exibirClienteCodigo(Integer.parseInt(codigo));
}//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        fechar();
}//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonExecutarPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarPesquisaActionPerformed
        /*Vector<Cliente> listaClientes = null;
        try {
        jTextAreaResposta.setText("");
        listaClientes = m_loc.buscarClientesPorNome(jTextFieldParametroNome.getText().trim());
        for (Cliente objCliente : listaClientes) {
        jTextAreaResposta.append(objCliente.toString() + "\n");
        }
        jTextAreaResposta.append("Nº de clientes encontrados: " + listaClientes.size() + "\n");
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(),
        "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
        }*/
        try {
            jScrollPane10.setViewportView(m_loc.buscarClientesPorNome(jTextFieldParametroNome.getText()));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Consulta de Clientes pelo Nome",
                    JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_jButtonExecutarPesquisaActionPerformed

    private void jButtonFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilmesActionPerformed

        JFrameFilmes JF_Filmes = new JFrameFilmes();
        JF_Filmes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonFilmesActionPerformed

    private void jButtonPrimeiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiro1ActionPerformed
        limparForm();
    }//GEN-LAST:event_jButtonPrimeiro1ActionPerformed

    private void jButtonLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocacaoActionPerformed
        JFrameLocar JF_Locar = new JFrameLocar();
        JF_Locar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLocacaoActionPerformed

    private void jButton3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3DActionPerformed
        JFrame3D JF_3D = new JFrame3D(this, true);
        JF_3D.setVisible(true);
    }//GEN-LAST:event_jButton3DActionPerformed

    private void jButtonExecutarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarConsultaActionPerformed

        try {
            String nome = jTextFieldParametroNome1.getText();
            if (!LtpUtil.validarData(jTextFieldParametroData1.getText()) || !LtpUtil.validarData(jTextFieldParametroData2.getText())) {
                JOptionPane.showMessageDialog(
                        this,
                        "Data Inválida",
                        "Consulta de Clientes pelo Período",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            DateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
            String as = jTextFieldParametroData1.getText();
            java.util.Date parsedUtilDate = formater.parse(as);
            java.sql.Date sqltDate = new java.sql.Date(parsedUtilDate.getTime());

            DateFormat formater2 = new SimpleDateFormat("dd/MM/yyyy");
            String as2 = jTextFieldParametroData2.getText();
            java.util.Date parsedUtilDate2 = formater2.parse(as2);
            java.sql.Date sqltDate2 = new java.sql.Date(parsedUtilDate2.getTime());

            jScrollPane11.setViewportView(m_loc.buscarClientesPorPeriodo(nome, sqltDate, sqltDate2));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Consulta de Clientes pelo Período",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExecutarConsultaActionPerformed

    private void jButtonExecutarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarRelatorioActionPerformed
        GregorianCalendar menorData = new GregorianCalendar();
        GregorianCalendar maiorData = new GregorianCalendar();
       
        if (!LtpUtil.validarData(jTextFieldParametroinicio.getText(), menorData)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Menor data inválida.",
                    "Relação de Clientes",
                    JOptionPane.WARNING_MESSAGE);
            jTextFieldParametroinicio.requestFocus();
            return;
        }
        if (!LtpUtil.validarData(jTextFieldParametrofim.getText(), maiorData)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Maior data inválida.",
                    "Relação de Clientes",
                    JOptionPane.WARNING_MESSAGE);
            jTextFieldParametrofim.requestFocus();
            return;
        }
        if (menorData.compareTo(maiorData)>0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Menor data maior que a maior data",
                    "Relação de Clientes",
                    JOptionPane.WARNING_MESSAGE);
            jTextFieldParametroinicio.requestFocus();
            return;
        }
        HashMap<String,Object> parametros = new HashMap<String, Object>();
        parametros.put("DATA", menorData.getTime());
        parametros.put("DATA2", maiorData.getTime());

        try {
            LtpUtil.gerarRelatorio(
                    LtpUtil.RELATORIO_VISUALIZADOR_JASPER,
                    bdlocadora.BDLocadora.objCon,
                    parametros,
                    getClass().getResource("relatorios/Relatorio_C.jasper").openStream(),
                    "Relação com Estatísticas de Clientes");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}//GEN-LAST:event_jButtonExecutarRelatorioActionPerformed

    private void jButtonExecutarRelatorioProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarRelatorioProvaActionPerformed
        HashMap<String,Object> parametros = new HashMap<String, Object>();
        parametros.put("mes", Integer.parseInt(jTextFieldParametroMes.getText()));
        parametros.put("ano", Integer.parseInt(jTextFieldParametroAno.getText()));

        try {
            LtpUtil.gerarRelatorio(
                    LtpUtil.RELATORIO_VISUALIZADOR_JASPER,
                    bdlocadora.BDLocadora.objCon,
                    parametros,
                    getClass().getResource("relatorios/Relatorio_Prova.jasper").openStream(),
                    "Relação de Clientes");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonExecutarRelatorioProvaActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3D;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExecutarConsulta;
    private javax.swing.JButton jButtonExecutarPesquisa;
    private javax.swing.JButton jButtonExecutarRelatorio;
    private javax.swing.JButton jButtonExecutarRelatorioProva;
    private javax.swing.JButton jButtonFilmes;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLocacao;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonPrimeiro1;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonRestaurar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldEmail;
    private javax.swing.JFormattedTextField jFormattedTextFieldNome;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3D;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelFilmes;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelHora1;
    private javax.swing.JLabel jLabelHora2;
    private javax.swing.JLabel jLabelHora3;
    private javax.swing.JLabel jLabelHora4;
    private javax.swing.JLabel jLabelLocacao;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemFechar;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuTemas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelCadastro2;
    private javax.swing.JPanel jPanelComandos;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelConsulta1;
    private javax.swing.JPanel jPanelConsulta2;
    private javax.swing.JPanel jPanelFichaCadastro;
    private javax.swing.JPanel jPanelParametro;
    private javax.swing.JPanel jPanelParametro1;
    private javax.swing.JPanel jPanelParametro2;
    private javax.swing.JPanel jPanelParametro3;
    private javax.swing.JPanel jPanelResposta;
    private javax.swing.JPanel jPanelResposta1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTabbedPane jTabbedPaneClientes;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableClientes1;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldParametroAno;
    private javax.swing.JTextField jTextFieldParametroData1;
    private javax.swing.JTextField jTextFieldParametroData2;
    private javax.swing.JTextField jTextFieldParametroMes;
    private javax.swing.JTextField jTextFieldParametroNome;
    private javax.swing.JTextField jTextFieldParametroNome1;
    private javax.swing.JTextField jTextFieldParametrofim;
    private javax.swing.JTextField jTextFieldParametroinicio;
    // End of variables declaration//GEN-END:variables

    private void fechar() {
        if (JOptionPane.showConfirmDialog(
                this,
                "Confirma a saída?",
                "Locadora",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            try {
                bdlocadora.BDLocadora.fecharConexao();
                dispose();
                System.exit(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                System.exit(1);
            }

        }
    }

    private void primeiro() {
        try {
            exibirCliente(m_loc.buscarClientePrimeiro());
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void anterior() {
        try {
            if (jTextFieldCodigo.getText().equals("") || jTextFieldCodigo == null) {
                primeiro();
                return;
            }
            exibirCliente(m_loc.buscarClienteAnterior(Integer.parseInt(jTextFieldCodigo.getText())));
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void proximo() {
        try {
            if (jTextFieldCodigo.getText().equals("") || jTextFieldCodigo == null) {
                primeiro();
                return;
            }
            exibirCliente(m_loc.buscarClienteProximo(Integer.parseInt(jTextFieldCodigo.getText())));
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void ultimo() {
        try {
            exibirCliente(m_loc.buscarClienteUltimo());
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void exibirClienteCodigo(int codigo) {
        try {
            exibirCliente(m_loc.buscarClientePorCodigo(codigo));
        } catch (SQLException e1) {
            JOptionPane.showMessageDialog(this, e1.getMessage(),
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void exibirCliente(Cliente objCliente) {
        jTextFieldCodigo.setText(String.valueOf(objCliente.getCodigo()));
        jFormattedTextFieldNome.setText(objCliente.getNome().trim());
        jFormattedTextFieldCPF.setText(objCliente.getCpf().trim());
        jFormattedTextFieldTelefone.setText(objCliente.getTelefone().trim());
        jFormattedTextFieldEmail.setText(objCliente.getEmail());
        jFormattedTextFieldData.setText(LtpUtil.formatarData(objCliente.getData(), "dd/MM/yyyy"));
    }

    private void limparForm() {
        jTextFieldCodigo.setText("");
        jFormattedTextFieldNome.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldTelefone.setText("");
        jFormattedTextFieldEmail.setText("");
        jFormattedTextFieldData.setText("");
    }

    private boolean validarAtualizacao() {

        if (jFormattedTextFieldNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Falta informar o nome do cliente.",
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldNome.requestFocus();
            return false;
        }
        if (jFormattedTextFieldCPF.getText().trim().equals("")
                || !LtpUtil.validarCPF(jFormattedTextFieldCPF.getText().trim())) {
            JOptionPane.showMessageDialog(this, "CPF Inválido.",
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldCPF.requestFocus();
            return false;
        }
        if (jFormattedTextFieldTelefone.getText().substring(1, 3).equals("  ")) {
            JOptionPane.showMessageDialog(this, "Falta informar o telefone do cliente.",
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldTelefone.requestFocus();
            return false;
        }
        if (!jFormattedTextFieldEmail.getText().trim().equals("")
                && !LtpUtil.validarEmail(jFormattedTextFieldEmail.getText().trim())) {
            JOptionPane.showMessageDialog(this, "E-Mail Inválido.",
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldEmail.requestFocus();
            return false;
        }
        if (!jFormattedTextFieldData.getText().trim().equals("")
                && !LtpUtil.validarData(jFormattedTextFieldData.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Data Inválida.",
                    "Cadastro de Clientes", JOptionPane.WARNING_MESSAGE);
            jFormattedTextFieldData.requestFocus();
            return false;
        }
        return true;
    }
}
