/*
 * SplashClientes.java
 *
 * Created on 04 de Novembro de 2011, 22:30
 */

package usuario;
/**
 *
 * @author  JP
 */
public class SplashLocadora extends javax.swing.JDialog {
    
    /** Creates new form SplashClientes */
    public SplashLocadora(java.awt.Frame parent, boolean modal) {

        super(parent, modal); 
        this.setUndecorated(true);
        initComponents();

        // Thread para evolução da barra de progresso
       Thread bp = new Thread(new Runnable() {
            int valor = 0;
            public void run() {
                do {
                   valor++;
                   jSliderBar.setValue(valor);
                    try {
                        Thread.sleep(100);
                    } catch (Exception ex) {
                    }                    
                } while (true);

            }
        });
        bp.start();

        this.setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSplash = new javax.swing.JPanel();
        jLabelImagem = new javax.swing.JLabel();
        jSliderBar = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Clientes");

        jPanelSplash.setBackground(new java.awt.Color(230, 230, 250));
        jPanelSplash.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2), " Locadora Ltda ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N

        jLabelImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario/recursos/3dimg.jpg"))); // NOI18N

        jSliderBar.setBackground(new java.awt.Color(230, 230, 250));
        jSliderBar.setForeground(new java.awt.Color(204, 204, 204));
        jSliderBar.setValue(0);
        jSliderBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jSliderBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSliderBar.setEnabled(false);
        jSliderBar.setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10));
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Loading...");

        javax.swing.GroupLayout jPanelSplashLayout = new javax.swing.GroupLayout(jPanelSplash);
        jPanelSplash.setLayout(jPanelSplashLayout);
        jPanelSplashLayout.setHorizontalGroup(
            jPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSplashLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSplashLayout.createSequentialGroup()
                        .addComponent(jLabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSplashLayout.createSequentialGroup()
                        .addGroup(jPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(123, 123, 123))))
        );
        jPanelSplashLayout.setVerticalGroup(
            jPanelSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSplashLayout.createSequentialGroup()
                .addComponent(jLabelImagem)
                .addGap(18, 18, 18)
                .addComponent(jSliderBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JPanel jPanelSplash;
    private javax.swing.JSlider jSliderBar;
    // End of variables declaration//GEN-END:variables
    
}
