package cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ValidadorCPF", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidadorCPF {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validaCPF", targetNamespace = "http://webservice/", className = "cliente.ValidaCPF")
    @ResponseWrapper(localName = "validaCPFResponse", targetNamespace = "http://webservice/", className = "cliente.ValidaCPFResponse")
    public String validaCPF(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
